2024-02-05T11:08:32.036-0600	[34mINFO[0m	clients/client_factory.go:60	logDir:</Users/davidhu0/Desktop/cs450-nacos/example/callerService/log>   cacheDir:</Users/davidhu0/Desktop/cs450-nacos/example/callerService/cache>
2024-02-05T11:08:32.038-0600	[34mINFO[0m	naming_client/push_receiver.go:81	udp server start, port: 55731
2024-02-05T11:08:32.038-0600	[34mINFO[0m	util/common.go:94	Local IP:10.105.211.71
2024-02-05T11:08:37.039-0600	[31mERROR[0m	nacos_server/nacos_server.go:235	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"10.105.211.71","clusters":"","healthyOnly":"false","namespaceId":"public","serviceName":"DEFAULT_GROUP@@HelloService","udpPort":"55731"}>, header:<{}>, call domain error:<Get "http://10.105.10.110:8848/nacos/v1/ns/instance/list?app=&clusters=&udpPort=55731&healthyOnly=false&clientIP=10.105.211.71&namespaceId=public&serviceName=DEFAULT_GROUP@@HelloService": context deadline exceeded (Client.Timeout exceeded while awaiting headers)> , result:<>
2024-02-05T11:08:37.040-0600	[31mERROR[0m	nacos_server/nacos_server.go:235	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"10.105.211.71","clusters":"","healthyOnly":"false","namespaceId":"public","serviceName":"DEFAULT_GROUP@@HelloService","udpPort":"55731"}>, header:<{}>, call domain error:<Get "http://10.105.10.110:8848/nacos/v1/ns/instance/list?udpPort=55731&healthyOnly=false&clientIP=10.105.211.71&namespaceId=public&serviceName=DEFAULT_GROUP@@HelloService&app=&clusters=": dial tcp 10.105.10.110:8848: connect: no route to host> , result:<>
2024-02-05T11:08:37.040-0600	[31mERROR[0m	nacos_server/nacos_server.go:235	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"10.105.211.71","clusters":"","healthyOnly":"false","namespaceId":"public","serviceName":"DEFAULT_GROUP@@HelloService","udpPort":"55731"}>, header:<{}>, call domain error:<Get "http://10.105.10.110:8848/nacos/v1/ns/instance/list?healthyOnly=false&clientIP=10.105.211.71&namespaceId=public&serviceName=DEFAULT_GROUP@@HelloService&app=&clusters=&udpPort=55731": dial tcp 10.105.10.110:8848: connect: host is down> , result:<>
2024-02-05T11:08:37.040-0600	[31mERROR[0m	naming_client/host_reactor.go:149	QueryList return error!serviceName:DEFAULT_GROUP@@HelloService cluster: err:retry3times request failed,err=Get "http://10.105.10.110:8848/nacos/v1/ns/instance/list?healthyOnly=false&clientIP=10.105.211.71&namespaceId=public&serviceName=DEFAULT_GROUP@@HelloService&app=&clusters=&udpPort=55731": dial tcp 10.105.10.110:8848: connect: host is down
2024-02-05T11:09:12.584-0600	[34mINFO[0m	clients/client_factory.go:60	logDir:</Users/davidhu0/Desktop/cs450-nacos/example/callerService/log>   cacheDir:</Users/davidhu0/Desktop/cs450-nacos/example/callerService/cache>
2024-02-05T11:09:12.585-0600	[34mINFO[0m	naming_client/push_receiver.go:81	udp server start, port: 54989
2024-02-05T11:09:12.585-0600	[34mINFO[0m	util/common.go:94	Local IP:10.105.211.71
2024-02-05T11:09:12.612-0600	[34mINFO[0m	naming_client/host_reactor.go:100	service not found in cache DEFAULT_GROUP@@HelloService
